version: '3.8'
services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=amauser
      - POSTGRES_PASSWORD=amapass
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_MULTIPLE_DATABASES="ama_dev,ama_test"
    ports:
      - 5432:5432
    volumes:
      - ./scripts/entrypoints:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
